# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'YBAutoLayout' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry'

  # Pods for YBAutoLayout

  target 'YBAutoLayoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YBAutoLayoutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
